# cannot use the default workflow (https://github.com/yext/slapshot-reusable-workflows)
# because of the monorepo structure
name: Check and Update Repo's documenation and third party notices

on: pull_request

jobs:
  update-docs-and-third-party-notices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci --ignore-scripts
      - run: npm run build
      - name: Update Documentation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated update to repo's documentation and third party notices from github action"
          add: '**/*.md **/THIRD-PARTY-NOTICES'
          push: true
          default_author: github_actions